setopt prompt_subst
setopt no_beep # don't beep on error
setopt interactive_comments # Allow comments even in interactive shells (especially for Muness)
setopt auto_cd # If you type foo, and it isn't a command, and it is a directory in your cdpath, go there
setopt cdablevarS # if argument to cd is the name of a parameter whose value is a valid directory, it will become the current directory
setopt pushd_ignore_dups # don't push multiple copies of the same directory onto the directory stack
setopt extended_glob # treat #, ~, and ^ as part of patterns for filename generation
setopt always_to_end # When completing from the middle of a word, move the cursor to the end of the word
setopt auto_menu # show completion menu on successive tab press. needs unsetop menu_complete to work
setopt auto_name_dirs # any parameter that is set to the absolute name of a directory immediately becomes a name for that directory
setopt complete_in_word # Allow completion from within a word/phrase

unsetopt menu_complete # do not autoselect the first completion entry

autoload -U colors && colors
autoload -Uz vcs_info

zstyle ':vcs_info:git*' formats "($fg[red]%b$reset_color) "
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' get-revision true
zstyle ':vcs_info:*' enable git

export LSCOLORS="Gxfxcxdxbxegedabagacad"
export SHELL=/usr/local/bin/zsh
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

bindkey -v

source $HOME/bin/ssh-find-agent.bash

# Autoload .env files
load_env_file() {
  if [ -f ".env" ]; then export $(grep -v '#' .env); fi;
}

# Load for .env files when changing dir
chpwd() { load_env_file }

alias be="bundle exec"

load_env_file

export GOPATH=$HOME/code/elcuervo/go
export GOSOURCE=$GOPATH/src/code.google.com/p/go
export NODE_PATH=/usr/local/lib/node_modules
export NPM_PATH=/usr/local/share/npm/bin
export BIN_PATH=$HOME/bin:$GOPATH/bin
export BREW_PATH=/usr/local/bin
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=$PATH:$BIN_PATH:$NODE_PATH:$NPM_PATH:$BREW_PATH:$GOSOURCE/bin

# Theme
precmd() {
  psvar=()

  vcs_info
  [[ -n $vcs_info_msg_0_ ]] && psvar[1]="$vcs_info_msg_0_"
}

export PROMPT='$fg_bold[white]%~$reset_color${vcs_info_msg_0_} '

set_ssh_agent_socket

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
chruby ruby-2.0

# Plugins
source ~/.zsh/aliases.sh
source ~/.zsh/tmux.sh

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
